### ISSUE TITLE
Add the Environment Indicator module

### ISSUE THREAD

**Issue by ozin7** [lemberg/draft#5]
Color indicators for environments. https://www.drupal.org/project/environment_indicator
Config example in the settings.php:
```
$config['environment_indicator.indicator']['bg_color'] = '#29aae1';
$config['environment_indicator.indicator']['fg_color'] = '#ffffff';
$config['environment_indicator.indicator']['name'] = 'Development';
```

**Comment by T2L** [comment]
Any ideas re colors?

**Comment by ozin7** [comment]
`$config['environment_indicator.indicator']['bg_color'] = `![#128A0C](https://placehold.it/15/128A0C/000000?text=+)`'#128A0C';`

`$config['environment_indicator.indicator']['fg_color'] = '#ffffff';`

`$config['environment_indicator.indicator']['name'] = 'Local';`

---

`$config['environment_indicator.indicator']['bg_color'] = `![#84b6eb](https://placehold.it/15/84b6eb/000000?text=+)`'#84b6eb';`

`$config['environment_indicator.indicator']['fg_color'] = '#ffffff';`

`$config['environment_indicator.indicator']['name'] = 'Develop';`

---

`$config['environment_indicator.indicator']['bg_color'] = `![#ede35e](https://placehold.it/15/ede35e/000000?text=+)`'#ede35e';`

`$config['environment_indicator.indicator']['fg_color'] = '#ffffff';`

`$config['environment_indicator.indicator']['name'] = 'Stage';`

---

`$config['environment_indicator.indicator']['bg_color'] = `![#c00c00](https://placehold.it/15/c00c00/000000?text=+)`'#c00c00';`

`$config['environment_indicator.indicator']['fg_color'] = '#ffffff';`

`$config['environment_indicator.indicator']['name'] = 'Production';`
